version: '3.7'

volumes:
  db: {}

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
      args:
        BOOKSTACK_VERSION: ${BOOKSTACK_VERSION}
    image: bookstack/nginx:${BOOKSTACK_VERSION}
    container_name: nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`bookstack.example.local`)"
      - "traefik.http.routers.bookstack.entrypoints=web"
    depends_on:
      - app
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - reverse-proxy
      - bookstack

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: php
      args:
        BOOKSTACK_VERSION: ${BOOKSTACK_VERSION}
    image: bookstack/app:${BOOKSTACK_VERSION}
    container_name: app
    depends_on:
      - mariadb
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: bookstack-test
      DB_USERNAME: bookstack-test
      DB_PASSWORD: bookstack-test
      MAIL_DRIVER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      APP_URL: http://bookstack.example.local
    volumes:
      - ./docker-entrypoint.sh:/root/docker-entrypoint.sh:ro
    networks:
      - bookstack

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_DATABASE: bookstack-test
      MYSQL_USER: bookstack-test
      MYSQL_PASSWORD: bookstack-test
      MYSQL_ROOT_PASSWORD: 'test'
    volumes:
      - db:/var/lib/mysql
    networks:
      - bookstack

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - ${DEV_MAIL_PORT:-8025}:8025
    networks:
      - bookstack

networks:
  reverse-proxy:
    external: true
  bookstack:
    external: true
